apiVersion: batch/v1
kind: Job
metadata:
  name: enterpriseinference-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: enterpriseinference-sa
      containers:
      - name: setup
        image: {{ .Values.main.image }}
        command: ["/bin/sh", "-c", "/scripts/ei_setup.sh"]
        resources:
          {{- toYaml .Values.main.resources | nindent 10 }}
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: workspace
          mountPath: /workspace
      restartPolicy: OnFailure
      volumes:
      - name: scripts
        configMap:
          name: enterpriseinference-scripts
      - name: workspace
        persistentVolumeClaim:
          claimName: enterpriseinference-pvc