apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enterpriseinference-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.main.persistence.size }}
  storageClassName: {{ .Values.main.config.storageClassName }}