apiVersion: v1
kind: Secret
metadata:
  name: enterpriseinference-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  hf-token: {{ .Values.main.secrets.huggingFaceToken | b64enc | quote }}