apiVersion: v1
kind: Service
metadata:
  name: model-serving-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: model-serving
  ports:
  - protocol: TCP
    port: {{ .Values.modelServing.service.port }}
    targetPort: {{ .Values.modelServing.service.targetPort }}