## Global settings
nameOverride: ""
fullnameOverride: ""
device: "hpu" # Options: hpu, cpu

## Enterprise Inference Main Component Settings
main:
  enabled: true
  
  # User configurable options from app spec
  config:
    # General config
      storageClassName: "gp2"  # Required: Storage class for the PVC
      clusterUrl: "api.example.com"  # The base URL to host the inference endpoint
      models: [1]  # A list of the model numbers from the list of pre-validated models
      cpuOrGpu: "gaudi3"  # The target platform to deploy the model [cpu, gpu, gaudi2, gaudi3]

      # Prerequisites config
      sshKeyName: "id_rsa"  # Name of the SSH key pair
      ipAddress: "127.0.0.1"  # IP address of the machine, default to localhost
      certsPath: "~/certs"

      # Inference deployment config
      certFile: "cert.pem"
      keyFile: "key.pem"
      keycloakClientId: "api"
      keycloakAdminUser: "api-admin"
      keycloakAdminPassword: "changeme!!"
      deployKubernetesFresh: "on"
      deployIngressController: "on"
      deployKeycloakApisix: "on"
      deployObservability: "on"
      deployLlmModels: "on"

  upstream:
   repository: "https://github.com/opea-project/Enterprise-Inference"
   branch: "main"
   configPath: "core/inference-config.cfg"

  # User configurable secrets from app spec
  secrets:
    huggingFaceToken: "hf_xxxxx"  # Hugging Face token to access models
  
  # Security context settings
  securityContext:
    enabled: true
    fsGroup: 0
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
  
  # Service configuration
  service:
    type: ClusterIP
    port: 8080

  # Resources for application
  resources:
    hpu:
      limits:
        cpu: "64"
        memory: "1024Gi"
        habana.ai/gaudi: "8"
      requests:
        cpu: "40"
        memory: "16Gi"
        habana.ai/gaudi: "1"
    cpu:
      limits:
        cpu: "64"
        memory: "1024Gi"
      requests:
        cpu: "40"
        memory: "16Gi"

  # Persistent volume claim
  persistence:
    enabled: true
    size: 10Gi
    # storageClassName is set from config.storageClassName

## Model Serving Component Settings
modelServing:
  enabled: false

  # Service configuration
  service:
    port: 8500
    targetPort: 8500

  # Resources for model serving
    resources:
    hpu:
      limits:
        cpu: "64"
        memory: "1024Gi"
        habana.ai/gaudi: "8"
      requests:
        cpu: "40"
        memory: "16Gi"
        habana.ai/gaudi: "1"
    cpu:
      limits:
        cpu: "64"
        memory: "1024Gi"
      requests:
        cpu: "40"
        memory: "16Gi"
